// the first in the list is the default

LM_TMAP(greedy, libmapping_mapping_algorithm_greedy_init, libmapping_mapping_algorithm_greedy_map, libmapping_mapping_algorithm_greedy_destroy)

LM_TMAP(greedylb, libmapping_mapping_algorithm_greedy_lb_init, libmapping_mapping_algorithm_greedy_lb_map, libmapping_mapping_algorithm_greedy_lb_destroy)

